package gestiondeunbanco.wilmervega.application.adapters.api.mappers;

import gestiondeunbanco.wilmervega.application.adapters.api.dto.CompanyClientRequest;
import gestiondeunbanco.wilmervega.domain.models.CompanyClient;
import gestiondeunbanco.wilmervega.domain.models.NaturalClient;
import org.springframework.stereotype.Component;

@Component
public class CompanyClientMapper {

    /**
     * Converts CompanyClientRequest DTO into the domain model CompanyClient.
     * Protects sensitive fields: does not set ID from request.
     * Sets legal representative as a reference only (ID is provided, not full entity).
     */
    public CompanyClient toModel(CompanyClientRequest request) {
        CompanyClient model = new CompanyClient();

        model.setBusinessName(request.getBusinessName());
        model.setDocumentNumber(request.getDocumentNumber());
        model.setEmail(request.getEmail());
        model.setPhone(request.getPhone());
        model.setAddress(request.getAddress());

        // Set legal representative reference if provided
        if (request.getLegalRepresentativeId() != null) {
            NaturalClient representative = new NaturalClient();
            representative.setId(request.getLegalRepresentativeId());
            model.setLegalRepresentative(representative);
        }

        // Do NOT set ID from request; it will be generated by persistence layer
        return model;
    }
}
