package gestiondeunbanco.wilmervega.application.adapters.api.mappers;

import gestiondeunbanco.wilmervega.application.adapters.api.dto.NaturalClientRequest;
import gestiondeunbanco.wilmervega.domain.models.NaturalClient;
import gestiondeunbanco.wilmervega.domain.models.SystemRole;
import org.springframework.stereotype.Component;

import java.util.Locale;

@Component
public class NaturalClientMapper {

    /**
     * Converts NaturalClientRequest DTO into the domain model NaturalClient.
     * Protects sensitive fields: does not set ID from request.
     */
    public NaturalClient toModel(NaturalClientRequest request) {
        NaturalClient model = new NaturalClient();

        model.setFullName(request.getFullName());
        model.setDocumentNumber(request.getDocumentNumber());
        model.setEmail(request.getEmail());
        model.setPhone(request.getPhone());
        model.setBirthDate(request.getBirthDate());
        model.setAddress(request.getAddress());

        // Set role, defaulting to NATURAL_CLIENT if not provided
        if (request.getRole() != null && !request.getRole().isBlank()) {
            model.setRole(SystemRole.valueOf(request.getRole().trim().toUpperCase(Locale.ROOT)));
        } else {
            model.setRole(SystemRole.NATURAL_CLIENT);
        }

        // Do NOT set ID from request; it will be generated by persistence layer
        return model;
    }
}
