spring.application.name=wilmer-vega

# -------------------------------------------------------
# H2 Database (en memoria - no requiere instalacion)
# -------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:bank_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# -------------------------------------------------------
# MongoDB Atlas (Bitacora / AuditLog - NoSQL)
# -------------------------------------------------------
# Define MONGODB_URI para Atlas o usa el valor local por defecto.
spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/bank_audit_db?connectTimeoutMS=5000&socketTimeoutMS=5000&serverSelectionTimeoutMS=5000}
spring.data.mongodb.database=${MONGODB_DATABASE:bank_audit_db}
app.mongodb.required=${MONGODB_REQUIRED:false}

# -------------------------------------------------------
# JWT Security
# -------------------------------------------------------
jwt.secret=ClinicAppSecretKeyForJsonWebTokenGeneration2026SecureKey
jwt.expirationMs=300000
