spring.application.name=wilmer-vega
server.port=8083

# -------------------------------------------------------
# H2 Database (In-Memory)
# -------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:bank_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# -------------------------------------------------------
# MongoDB embebido (Flapdoodle) - sin instalación requerida
# -------------------------------------------------------
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/bank_audit_db
spring.data.mongodb.database=bank_audit_db
app.mongodb.required=false

# -------------------------------------------------------
# JWT Security
# -------------------------------------------------------
jwt.secret=ClinicAppSecretKeyForJsonWebTokenGeneration2026SecureKey
# JWT duration: 24 hours
jwt.expirationMs=86400000
